PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS UserAcc;
CREATE TABLE UserAcc(
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL,
    pass_hash TEXT NOT NULL,
    email TEXT NOT NULL
);

DROP TABLE IF EXISTS Map;
CREATE TABLE Map(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    owner INTEGER REFERENCES UserAcc(id),
    rating INTEGER
);

DROP TABLE IF EXISTS MapLine;
CREATE TABLE MapLine(
    id INTEGER PRIMARY KEY,
    draw TEXT NOT NULL,
    map_id INTEGER REFERENCES Map(id) ON DELETE CASCADE
);
